import CryptoKit
import Observation
import SwiftUI
import UserNotifications
import UniformTypeIdentifiers
#if canImport(PDFKit)
import PDFKit
#endif
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

struct AlphaAskCaseScreen: View {
    @Bindable var model: AlphaRossModel
    let caseId: UUID

    var body: some View {
        AlphaAskConversationScreen(model: model, fixedScopeCaseID: caseId)
    }
}

struct AlphaExportsScreen: View {
    @Bindable var model: AlphaRossModel
    let caseId: UUID?

    private var visibleReports: [AlphaExportedReport] {
        model.persisted.exports.filter { report in
            caseId == nil || report.caseId == caseId
        }
    }

    var body: some View {
        ScrollView {
            RossGlassGroup(spacing: alphaSectionSpacing) {
                VStack(alignment: .leading, spacing: alphaSectionSpacing) {
                    AlphaInlineHeader(
                    eyebrow: nil,
                    title: "Notes & Drafts",
                    detail: "Generate local notes and drafts for advocate review."
                )

                RossSectionCard(title: "Generate") {
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Use the compact actions here, or type “draft case note” in Ask Ross below.")
                            .font(.subheadline)
                            .foregroundStyle(Color.rossInk.opacity(0.72))

                        RossGlassGroup(spacing: 10) {
                            VStack(alignment: .leading, spacing: 10) {
                                HStack(spacing: 10) {
                                    AlphaCompactDraftActionButton(title: "Chronology", systemImage: "list.bullet.rectangle") {
                                        Task { await model.generateExport(kind: "chronology_report", caseId: caseId) }
                                    }
                                    AlphaCompactDraftActionButton(title: "Case note", systemImage: "square.and.pencil") {
                                        Task { await model.generateExport(kind: "case_note", caseId: caseId) }
                                    }
                                }

                                HStack(spacing: 10) {
                                    AlphaCompactDraftActionButton(title: "Order summary", systemImage: "doc.plaintext") {
                                        Task { await model.generateExport(kind: "order_summary", caseId: caseId) }
                                    }
                                    AlphaCompactDraftActionButton(title: "Transcript", systemImage: "bubble.left.and.text.bubble.right") {
                                        Task { await model.generateExport(kind: "chat_transcript", caseId: caseId) }
                                    }
                                }
                            }
                        }
                    }
                }

                RossSectionCard(title: "Before you file") {
                    Text("This draft was generated by AI. Review all content carefully. Ross is a tool to help you work faster, not a substitute for your professional judgement.")
                        .font(.footnote)
                        .foregroundStyle(Color.rossInk.opacity(0.72))
                        .fixedSize(horizontal: false, vertical: true)
                }

                if visibleReports.isEmpty {
                    RossSectionCard(title: "No drafts yet") {
                        Text("Generate a case note, chronology, order summary, or transcript to keep a local draft ready for advocate review.")
                            .font(.subheadline)
                            .foregroundStyle(Color.rossInk.opacity(0.7))
                    }
                }

                ForEach(visibleReports) { report in
                    RossSectionCard(title: report.title, subtitle: report.kind.replacingOccurrences(of: "_", with: " ").capitalized) {
                        VStack(alignment: .leading, spacing: 12) {
                            AlphaExportReviewMetadata(report: report)

                            Text("Review this draft before sending or filing. Sharing uses the iOS share sheet and keeps the saved draft on this device.")
                                .font(.caption)
                                .foregroundStyle(Color.rossInk.opacity(0.68))
                                .fixedSize(horizontal: false, vertical: true)

                            ShareLink(item: model.exportURL(for: report)) {
                                Label("Review or share draft", systemImage: "square.and.arrow.up")
                                    .frame(maxWidth: .infinity)
                            }
                            .rossGlassButtonStyle(tint: Color.rossAccent, cornerRadius: 16)
                        }
                    }
                }
                }
                .padding(alphaScreenPadding)
            }
        }
        .navigationTitle("Notes & Drafts")
        .rossInlineNavigationTitle()
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                AlphaAskToolbarButton(systemImage: "bubble.right", accessibilityLabel: "Open Ask Ross") {
                    if let caseId {
                        model.openAsk(scopeCaseID: caseId)
                    } else {
                        model.openAsk()
                    }
                }
            }
        }
    }
}

private struct AlphaExportReviewMetadata: View {
    let report: AlphaExportedReport

    private var createdLabel: String {
        report.createdAt.formatted(date: .abbreviated, time: .shortened)
    }

    private var kindLabel: String {
        report.kind.replacingOccurrences(of: "_", with: " ").capitalized
    }

    private var fileName: String {
        URL(fileURLWithPath: report.relativePath).lastPathComponent
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            AlphaSettingsValueRow(label: "Draft type", value: kindLabel)
            AlphaSettingsValueRow(label: "Created", value: createdLabel)
            AlphaSettingsValueRow(label: "Saved file", value: fileName)
        }
        .padding(12)
        .rossGlassSurface(
            tint: Color.rossHighlight.opacity(0.12),
            cornerRadius: 16,
            shadowOpacity: 0.05,
            shadowRadius: 5,
            shadowY: 2,
            strokeOpacity: 0.46
        )
    }
}
