#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRATCH_PATH="${ROSS_SWIFTPM_SCRATCH_PATH:-$ROOT_DIR/ios/build-test/swiftpm}"

RUNTIME_FILTER='AlphaExtractionTests/(testRuntimeIdentityLineIncludesGGUFDraftBenchmarkFields|testRuntimeIdentityLineIncludesRejectedGGUFDraftCandidateWithoutClaimingAcceleration|testRuntimeIdentityLineIncludesMLXDirectoryFields|testRuntimeIdentityLineIncludesUnavailableMLXDraftCandidate|testRuntimeIdentityLineIncludesCoreAISystemFields|testRuntimeHealthRejectsMLXRequestAgainstGGUFPackBeforeFallback|testRuntimeHealthRejectsCoreAIRequestAgainstGGUFPackBeforeFallback|testExplicitMLXRuntimeRequestDoesNotFallBackToGGUFProvider|testExplicitCoreMLRuntimeRequestDoesNotFallBackToGGUFProvider|testRuntimeIdentityLineIncludesMissingCoreAIArtifactForExplicitCoreMLWithoutSentinel|testRuntimeIdentityLineIncludesMissingMLXArtifactForExplicitMLXWithoutBorrowingGGUF|testExperimentalGGUFProviderAllowsLowTokenDraftAccelerationForConstrainedQuickStartE4B|testExperimentalGGUFProviderBlocksConstrainedE4BDraftBeforeMemoryRiskyValidation|testExperimentalGGUFProviderUsesStrictDraftContextWhenSmokeRequiresDraftAcceleration|testExperimentalGGUFProviderReportsStrictDraftContextFailureWithoutFallback|testExperimentalGGUFProviderFailsStrictDraftProofWhenContextRunsStandard|testRuntimeHealthMarksConfiguredGGUFFileAsMissingMLXArtifact|testMLXRunReturnsMissingArtifactCategoryBeforeGeneration|testRuntimeHealthKeepsMLXAvailableWithInvalidDraftArtifactWithoutClaimingAcceleration|testExperimentalMLXProviderRunsStandardGenerationWhenDraftArtifactIsInvalid|testExperimentalMLXProviderDoesNotFallbackWhenSmokeRequiresDraftAcceleration|testFoundationProviderReportsMissingAdapterArtifactBeforeGeneration|testFoundationProviderReportsUnsupportedPlatformBeforeGeneration)'

cd "$ROOT_DIR"
echo "Running SwiftPM iOS runtime identity/guardrail tests..."
swift test \
  --package-path ios \
  --scratch-path "$SCRATCH_PATH" \
  --filter "$RUNTIME_FILTER"
