#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRATCH_PATH="${ROSS_SWIFTPM_SCRATCH_PATH:-$ROOT_DIR/ios/build-test/swiftpm}"

REQUIRED_TESTS=(
  testRuntimeIdentityLineIncludesGGUFDraftBenchmarkFields
  testRuntimeIdentityLineReportsSimulatorGGUFCPUOffload
  testRuntimeEnvironmentParsesPhysicalMemoryOverrideForSimulatorSmoke
  testRuntimeIdentityLineIncludesRejectedGGUFDraftCandidateWithoutClaimingAcceleration
  testRuntimeIdentityLineIncludesMLXDirectoryFields
  testRuntimeIdentityLineIncludesUnavailableMLXDraftCandidate
  testRuntimeIdentityLineIncludesCoreAISystemFields
  testRuntimeIdentityLineUsesActualUnavailableCoreAIProviderName
  testRuntimeIdentityPreflightProviderNamesStayRuntimeSpecific
  testMissingActivePackErrorsStayRuntimeSpecific
  testRuntimeIdentityLineMarksDeterministicProviderAsFallback
  testAskResultPreservesModelInvocationForAnswerDetails
  testAnswerDetailOverviewMetricsPreferMeasuredTokenCountLabel
  testAnswerDetailOverviewMetricsMarkEstimatedTokenSpeedAsApproximate
  testAnswerDetailOverviewMetricsIncludeSourceCoverageWhenAvailable
  testRuntimeHealthRejectsMLXRequestAgainstGGUFPackBeforeFallback
  testRuntimeHealthRejectsCoreAIRequestAgainstGGUFPackBeforeFallback
  testExplicitMLXRuntimeRequestDoesNotFallBackToGGUFProvider
  testExplicitCoreMLRuntimeRequestDoesNotFallBackToGGUFProvider
  testRuntimeIdentityLineIncludesMissingCoreAIArtifactForExplicitCoreMLWithoutSentinel
  testExplicitCoreMLRuntimeRequestRejectsForeignDebugPathWithoutKindBeforeProviderConstruction
  testRuntimeHealthRejectsFileBackedSystemKindBeforeProviderConstruction
  testRuntimeIdentityLineIncludesMissingMLXArtifactForExplicitMLXWithoutBorrowingGGUF
  testDebugLocalModelSmokePackRejectsMissingRuntimeArtifactKind
  testExplicitCoreAIAdapterPathOverridesActiveSystemSentinel
  testInstalledModelSmokePackTargetsExactPackIDOverride
  testInstalledModelSmokePackPrefersRequestedRuntimeOverActiveFallback
  testInstalledModelSmokePackFailsClosedForMissingRequestedRuntime
  testExperimentalGGUFProviderAllowsLowTokenDraftAccelerationForConstrainedQuickStartE4B
  testExperimentalGGUFProviderBlocksConstrainedE4BDraftBeforeMemoryRiskyValidation
  testExperimentalGGUFProviderUsesStrictDraftContextWhenSmokeRequiresDraftAcceleration
  testExperimentalGGUFProviderReportsStrictDraftContextFailureWithoutFallback
  testExperimentalGGUFProviderFailsStrictDraftProofWhenContextRunsStandard
  testExperimentalGGUFProviderDoesNotPassInvalidDraftArtifactToGenerationContext
  testRuntimeHealthMarksConfiguredGGUFFileAsMissingMLXArtifact
  testPreparedMLXRuntimeDirectoryPatchesGemma4SharedKVWeightMap
  testMLXRunReturnsMissingArtifactCategoryBeforeGeneration
  testRuntimeHealthMarksUnsupportedGemma4MultimodalMLXArchiveUnavailable
  testMLXRunReturnsUnsupportedArchiveCategoryBeforeGeneration
  testRuntimeHealthKeepsMLXAvailableWithInvalidDraftArtifactWithoutClaimingAcceleration
  testExperimentalMLXProviderRunsStandardGenerationWhenDraftArtifactIsInvalid
  testExperimentalMLXProviderFailsClosedWhenExplicitDraftGenerationFails
  testExperimentalMLXProviderDoesNotFallbackWhenSmokeRequiresDraftAcceleration
  testFoundationProviderReportsSpecificGenerationFailure
  testFoundationProviderReportsMissingAdapterArtifactBeforeGeneration
  testFoundationProviderReportsEmptyAdapterArtifactsBeforeGeneration
  testFoundationProviderRejectsNonAdapterPathShapeBeforeGeneration
  testRuntimeHealthRejectsCoreMLKindWithNonAdapterPathShape
  testFoundationProviderReportsForeignAdapterArtifactsBeforeGeneration
  testFoundationProviderReportsUnsupportedPlatformBeforeGeneration
)

TEST_SOURCE="$ROOT_DIR/ios/Tests/RossTests/AlphaExtractionTests.swift"
for test_name in "${REQUIRED_TESTS[@]}"; do
  if ! grep -q "func ${test_name}" "$TEST_SOURCE"; then
    echo "Missing required runtime guardrail test: ${test_name}" >&2
    exit 1
  fi
done

RUNTIME_FILTER="AlphaExtractionTests/($(IFS='|'; echo "${REQUIRED_TESTS[*]}"))"

cd "$ROOT_DIR"
echo "Running ${#REQUIRED_TESTS[@]} SwiftPM iOS runtime identity/guardrail tests..."
swift test \
  --package-path ios \
  --scratch-path "$SCRATCH_PATH" \
  --filter "$RUNTIME_FILTER"
